#define CONFIG_DEBUG

#define CONFIG_SUBSYS_PCI
#define CONFIG_SUBSYS_NET

#define CONFIG_DRV_E1000

#define CONFIG_DRV_PC8250_SERIAL
#define CONFIG_DRV_VGA_TEXT
#define CONFIG_DRV_PS2
#define CONFIG_DRV_VESA
#define CONFIG_DRV_SPLASH
#define CONFIG_DRV_RAMDISK_MULTIBOOT

#define CONFIG_DRV_DEVFS
#define CONFIG_DRV_FATFS
#define CONFIG_DRV_GPT
#define CONFIG_DRV_MBR

#define CONFIG_DRV_ATA_PIO
#define CONFIG_DRV_ATA

#define CONFIG_PROC_MAX_THREADS 128

#define CONFIG_MAX_EVENT_SUBSCRIBERS 128 // no reason to adjust
#define CONFIG_MAX_CORES 64
#define CONFIG_STACK_SIZE  0x40000

#define CONFIG_CONSOLE_BUFF_SZ 256
#define CONFIG_CONSOLE_POOL_SZ 32

#define CONFIG_VFS_NAME_MAX 256
