// #define CONFIG_DEBUG

#define CONFIG_DRV_PC8250_SERIAL
#define CONFIG_DRV_VGA_TEXT
#define CONFIG_DRV_PS2_KBD

#define CONFIG_DRV_ATA_PIO
#define CONFIG_DRV_ATA

#define CONFIG_MAX_CORES 64
#define CONFIG_STACK_SIZE 0x4000

#define CONFIG_CONSOLE_BUFF_SZ 128
#define CONFIG_CONSOLE_POOL_SZ 16
