#ifndef _INARI_CURSOR_H
#define _INARI_CURSOR_H

#define MOUSE_WIDTH  16
#define MOUSE_HEIGHT 16

#define T_CLR 0
#define B_CLR 0x01
#define W_CLR 0xFF
#define G_CLR 0xCC
#define D_CLR 0x66


__attribute__((unused)) static uint8_t cursor_hand[MOUSE_HEIGHT][MOUSE_WIDTH] = {
    { T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, B_CLR, B_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR },
    { T_CLR, T_CLR, T_CLR, T_CLR, B_CLR, W_CLR, W_CLR, B_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR },
    { T_CLR, T_CLR, T_CLR, T_CLR, B_CLR, W_CLR, W_CLR, B_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR },
    { T_CLR, T_CLR, T_CLR, T_CLR, B_CLR, W_CLR, W_CLR, B_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR },
    { T_CLR, T_CLR, T_CLR, T_CLR, B_CLR, W_CLR, W_CLR, B_CLR, B_CLR, B_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR },
    { T_CLR, T_CLR, T_CLR, T_CLR, B_CLR, W_CLR, W_CLR, B_CLR, W_CLR, W_CLR, B_CLR, B_CLR, T_CLR, T_CLR, T_CLR, T_CLR },
    { T_CLR, T_CLR, T_CLR, T_CLR, B_CLR, W_CLR, W_CLR, B_CLR, W_CLR, W_CLR, B_CLR, W_CLR, B_CLR, B_CLR, T_CLR, T_CLR },
    { T_CLR, T_CLR, B_CLR, B_CLR, B_CLR, W_CLR, W_CLR, B_CLR, W_CLR, W_CLR, B_CLR, W_CLR, W_CLR, W_CLR, B_CLR, T_CLR },
    { T_CLR, B_CLR, W_CLR, W_CLR, B_CLR, W_CLR, W_CLR, W_CLR, W_CLR, W_CLR, W_CLR, W_CLR, W_CLR, W_CLR, B_CLR, T_CLR },
    { T_CLR, B_CLR, W_CLR, W_CLR, W_CLR, W_CLR, W_CLR, W_CLR, W_CLR, W_CLR, W_CLR, W_CLR, W_CLR, W_CLR, B_CLR, T_CLR },
    { T_CLR, T_CLR, B_CLR, W_CLR, W_CLR, W_CLR, W_CLR, W_CLR, W_CLR, W_CLR, W_CLR, W_CLR, W_CLR, B_CLR, T_CLR, T_CLR },
    { T_CLR, T_CLR, T_CLR, B_CLR, W_CLR, W_CLR, W_CLR, W_CLR, W_CLR, W_CLR, W_CLR, W_CLR, W_CLR, B_CLR, T_CLR, T_CLR },
    { T_CLR, T_CLR, T_CLR, B_CLR, W_CLR, W_CLR, W_CLR, W_CLR, W_CLR, W_CLR, W_CLR, W_CLR, W_CLR, B_CLR, T_CLR, T_CLR },
    { T_CLR, T_CLR, T_CLR, T_CLR, B_CLR, W_CLR, W_CLR, W_CLR, W_CLR, W_CLR, W_CLR, W_CLR, B_CLR, T_CLR, T_CLR, T_CLR },
    { T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, B_CLR, W_CLR, W_CLR, W_CLR, W_CLR, W_CLR, W_CLR, B_CLR, T_CLR, T_CLR, T_CLR },
    { T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, B_CLR, B_CLR, B_CLR, B_CLR, B_CLR, B_CLR, T_CLR, T_CLR, T_CLR, T_CLR }
};

__attribute__((unused)) static uint8_t cursor_hourglass[MOUSE_HEIGHT][MOUSE_WIDTH] = {
    { T_CLR, T_CLR, T_CLR, B_CLR, B_CLR, B_CLR, B_CLR, B_CLR, B_CLR, B_CLR, B_CLR, B_CLR, B_CLR, T_CLR, T_CLR, T_CLR },
    { T_CLR, T_CLR, T_CLR, B_CLR, W_CLR, W_CLR, W_CLR, W_CLR, W_CLR, W_CLR, W_CLR, W_CLR, B_CLR, T_CLR, T_CLR, T_CLR },
    { T_CLR, T_CLR, T_CLR, B_CLR, B_CLR, B_CLR, B_CLR, B_CLR, B_CLR, B_CLR, B_CLR, B_CLR, B_CLR, T_CLR, T_CLR, T_CLR },
    { T_CLR, T_CLR, T_CLR, T_CLR, B_CLR, W_CLR, W_CLR, W_CLR, W_CLR, W_CLR, W_CLR, B_CLR, T_CLR, T_CLR, T_CLR, T_CLR },
    { T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, B_CLR, W_CLR, W_CLR, W_CLR, W_CLR, B_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR },
    { T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, B_CLR, W_CLR, W_CLR, B_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR },
    { T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, B_CLR, B_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR },
    { T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, B_CLR, B_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR },
    { T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, B_CLR, W_CLR, W_CLR, B_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR },
    { T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, B_CLR, W_CLR, W_CLR, W_CLR, B_CLR, B_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR },
    { T_CLR, T_CLR, T_CLR, T_CLR, B_CLR, W_CLR, W_CLR, W_CLR, W_CLR, W_CLR, W_CLR, B_CLR, T_CLR, T_CLR, T_CLR, T_CLR },
    { T_CLR, T_CLR, T_CLR, B_CLR, W_CLR, W_CLR, W_CLR, W_CLR, W_CLR, W_CLR, W_CLR, W_CLR, B_CLR, T_CLR, T_CLR, T_CLR },
    { T_CLR, T_CLR, T_CLR, B_CLR, B_CLR, B_CLR, B_CLR, B_CLR, B_CLR, B_CLR, B_CLR, B_CLR, B_CLR, T_CLR, T_CLR, T_CLR },
    { T_CLR, T_CLR, T_CLR, B_CLR, W_CLR, W_CLR, W_CLR, W_CLR, W_CLR, W_CLR, W_CLR, W_CLR, B_CLR, T_CLR, T_CLR, T_CLR },
    { T_CLR, T_CLR, T_CLR, B_CLR, B_CLR, B_CLR, B_CLR, B_CLR, B_CLR, B_CLR, B_CLR, B_CLR, B_CLR, T_CLR, T_CLR, T_CLR },
    { T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR }
};

__attribute__((unused)) static uint8_t cursor_ibeam[MOUSE_HEIGHT][MOUSE_WIDTH] = {
    { T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, B_CLR, B_CLR, B_CLR, B_CLR, B_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR },
    { T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, B_CLR, W_CLR, W_CLR, W_CLR, B_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR },
    { T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, B_CLR, B_CLR, W_CLR, B_CLR, B_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR },
    { T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, B_CLR, W_CLR, B_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR },
    { T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, B_CLR, W_CLR, B_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR },
    { T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, B_CLR, W_CLR, B_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR },
    { T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, B_CLR, W_CLR, B_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR },
    { T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, B_CLR, W_CLR, B_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR },
    { T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, B_CLR, W_CLR, B_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR },
    { T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, B_CLR, W_CLR, B_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR },
    { T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, B_CLR, W_CLR, B_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR },
    { T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, B_CLR, W_CLR, B_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR },
    { T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, B_CLR, W_CLR, B_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR },
    { T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, B_CLR, B_CLR, W_CLR, B_CLR, B_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR },
    { T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, B_CLR, W_CLR, W_CLR, W_CLR, B_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR },
    { T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, B_CLR, B_CLR, B_CLR, B_CLR, B_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR }
};

__attribute__((unused)) static uint8_t cursor_normal[MOUSE_HEIGHT][MOUSE_WIDTH] = {
    { B_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR },
    { B_CLR, B_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR },
    { B_CLR, W_CLR, B_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR },
    { B_CLR, W_CLR, W_CLR, B_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR },
    { B_CLR, W_CLR, W_CLR, W_CLR, B_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR },
    { B_CLR, W_CLR, W_CLR, W_CLR, W_CLR, B_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR },
    { B_CLR, W_CLR, W_CLR, W_CLR, W_CLR, W_CLR, B_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR },
    { B_CLR, W_CLR, W_CLR, W_CLR, W_CLR, W_CLR, W_CLR, B_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR },
    { B_CLR, W_CLR, W_CLR, W_CLR, W_CLR, W_CLR, W_CLR, W_CLR, B_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR },
    { B_CLR, W_CLR, W_CLR, W_CLR, W_CLR, W_CLR, W_CLR, W_CLR, W_CLR, B_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR },
    { B_CLR, W_CLR, W_CLR, W_CLR, W_CLR, W_CLR, B_CLR, B_CLR, B_CLR, B_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR },
    { B_CLR, W_CLR, W_CLR, B_CLR, W_CLR, W_CLR, B_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR },
    { B_CLR, W_CLR, B_CLR, T_CLR, B_CLR, W_CLR, W_CLR, B_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR },
    { B_CLR, B_CLR, T_CLR, T_CLR, B_CLR, W_CLR, W_CLR, B_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR },
    { T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, B_CLR, W_CLR, W_CLR, B_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR },
    { T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, B_CLR, B_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR, T_CLR }
};

__attribute__((unused)) static uint8_t btn_minimize[16][16] = {
    { W_CLR, W_CLR, W_CLR, W_CLR, W_CLR, W_CLR, W_CLR, W_CLR, W_CLR, W_CLR, W_CLR, W_CLR, W_CLR, W_CLR, W_CLR, B_CLR },
    { W_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, D_CLR, B_CLR },
    { W_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, D_CLR, B_CLR },
    { W_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, D_CLR, B_CLR },
    { W_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, D_CLR, B_CLR },
    { W_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, D_CLR, B_CLR },
    { W_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, D_CLR, B_CLR },
    { W_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, D_CLR, B_CLR },
    { W_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, D_CLR, B_CLR },
    { W_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, D_CLR, B_CLR },
    { W_CLR, G_CLR, G_CLR, G_CLR, B_CLR, B_CLR, B_CLR, B_CLR, B_CLR, B_CLR, B_CLR, B_CLR, G_CLR, G_CLR, D_CLR, B_CLR },
    { W_CLR, G_CLR, G_CLR, G_CLR, B_CLR, B_CLR, B_CLR, B_CLR, B_CLR, B_CLR, B_CLR, B_CLR, G_CLR, G_CLR, D_CLR, B_CLR },
    { W_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, D_CLR, B_CLR },
    { W_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, D_CLR, B_CLR },
    { W_CLR, D_CLR, D_CLR, D_CLR, D_CLR, D_CLR, D_CLR, D_CLR, D_CLR, D_CLR, D_CLR, D_CLR, D_CLR, D_CLR, D_CLR, B_CLR },
    { B_CLR, B_CLR, B_CLR, B_CLR, B_CLR, B_CLR, B_CLR, B_CLR, B_CLR, B_CLR, B_CLR, B_CLR, B_CLR, B_CLR, B_CLR, B_CLR }
};

__attribute__((unused)) static uint8_t btn_maximize[16][16] = {
    { W_CLR, W_CLR, W_CLR, W_CLR, W_CLR, W_CLR, W_CLR, W_CLR, W_CLR, W_CLR, W_CLR, W_CLR, W_CLR, W_CLR, W_CLR, B_CLR },
    { W_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, D_CLR, B_CLR },
    { W_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, D_CLR, B_CLR },
    { W_CLR, G_CLR, G_CLR, G_CLR, B_CLR, B_CLR, B_CLR, B_CLR, B_CLR, B_CLR, B_CLR, B_CLR, G_CLR, G_CLR, D_CLR, B_CLR },
    { W_CLR, G_CLR, G_CLR, G_CLR, B_CLR, B_CLR, B_CLR, B_CLR, B_CLR, B_CLR, B_CLR, B_CLR, G_CLR, G_CLR, D_CLR, B_CLR },
    { W_CLR, G_CLR, G_CLR, G_CLR, B_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, B_CLR, G_CLR, G_CLR, D_CLR, B_CLR },
    { W_CLR, G_CLR, G_CLR, G_CLR, B_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, B_CLR, G_CLR, G_CLR, D_CLR, B_CLR },
    { W_CLR, G_CLR, G_CLR, G_CLR, B_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, B_CLR, G_CLR, G_CLR, D_CLR, B_CLR },
    { W_CLR, G_CLR, G_CLR, G_CLR, B_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, B_CLR, G_CLR, G_CLR, D_CLR, B_CLR },
    { W_CLR, G_CLR, G_CLR, G_CLR, B_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, B_CLR, G_CLR, G_CLR, D_CLR, B_CLR },
    { W_CLR, G_CLR, G_CLR, G_CLR, B_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, B_CLR, G_CLR, G_CLR, D_CLR, B_CLR },
    { W_CLR, G_CLR, G_CLR, G_CLR, B_CLR, B_CLR, B_CLR, B_CLR, B_CLR, B_CLR, B_CLR, B_CLR, G_CLR, G_CLR, D_CLR, B_CLR },
    { W_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, D_CLR, B_CLR },
    { W_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, D_CLR, B_CLR },
    { W_CLR, D_CLR, D_CLR, D_CLR, D_CLR, D_CLR, D_CLR, D_CLR, D_CLR, D_CLR, D_CLR, D_CLR, D_CLR, D_CLR, D_CLR, B_CLR },
    { B_CLR, B_CLR, B_CLR, B_CLR, B_CLR, B_CLR, B_CLR, B_CLR, B_CLR, B_CLR, B_CLR, B_CLR, B_CLR, B_CLR, B_CLR, B_CLR }
};

__attribute__((unused)) static uint8_t btn_close[16][16] = {
    { W_CLR, W_CLR, W_CLR, W_CLR, W_CLR, W_CLR, W_CLR, W_CLR, W_CLR, W_CLR, W_CLR, W_CLR, W_CLR, W_CLR, W_CLR, B_CLR },
    { W_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, D_CLR, B_CLR },
    { W_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, D_CLR, B_CLR },
    { W_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, D_CLR, B_CLR },
    { W_CLR, G_CLR, G_CLR, G_CLR, B_CLR, B_CLR, G_CLR, G_CLR, G_CLR, G_CLR, B_CLR, B_CLR, G_CLR, G_CLR, D_CLR, B_CLR },
    { W_CLR, G_CLR, G_CLR, G_CLR, G_CLR, B_CLR, B_CLR, G_CLR, G_CLR, B_CLR, B_CLR, G_CLR, G_CLR, G_CLR, D_CLR, B_CLR },
    { W_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, B_CLR, B_CLR, B_CLR, B_CLR, G_CLR, G_CLR, G_CLR, G_CLR, D_CLR, B_CLR },
    { W_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, B_CLR, B_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, D_CLR, B_CLR },
    { W_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, B_CLR, B_CLR, B_CLR, B_CLR, G_CLR, G_CLR, G_CLR, G_CLR, D_CLR, B_CLR },
    { W_CLR, G_CLR, G_CLR, G_CLR, G_CLR, B_CLR, B_CLR, G_CLR, G_CLR, B_CLR, B_CLR, G_CLR, G_CLR, G_CLR, D_CLR, B_CLR },
    { W_CLR, G_CLR, G_CLR, G_CLR, B_CLR, B_CLR, G_CLR, G_CLR, G_CLR, G_CLR, B_CLR, B_CLR, G_CLR, G_CLR, D_CLR, B_CLR },
    { W_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, D_CLR, B_CLR },
    { W_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, D_CLR, B_CLR },
    { W_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, G_CLR, D_CLR, B_CLR },
    { W_CLR, D_CLR, D_CLR, D_CLR, D_CLR, D_CLR, D_CLR, D_CLR, D_CLR, D_CLR, D_CLR, D_CLR, D_CLR, D_CLR, D_CLR, B_CLR },
    { B_CLR, B_CLR, B_CLR, B_CLR, B_CLR, B_CLR, B_CLR, B_CLR, B_CLR, B_CLR, B_CLR, B_CLR, B_CLR, B_CLR, B_CLR, B_CLR }
};

#endif